apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-server
  template:
    metadata:
      labels:
        app: kafka-server
    spec:
      containers:
        - name: kafka-server
          image: {{ .Values.kafka.image }}
          env:
            - name: KAFKA_BROKER_ID
              value: "{{ .Values.kafka.brokerId }}"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: KAFKA_LISTENERS
              value: "{{ .Values.kafka.listeners }}"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "{{ .Values.kafka.advertisedListeners }}"
          ports:
            - containerPort: 9092
