apiVersion: v1
kind: Service
metadata:
  name: telemetry-db
spec:
  type: NodePort
  selector:
    app: telemetry-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 32432
