openapi: "3.0.2"
info:
  title: Telemetry Management API
  version: 1.0.0
  description: API для управления телеметрией.

servers:
  - url: "{protocol}://{host}:{port}/api"
    description: Локальный сервер для управления телеметрией
    variables:
      protocol:
        enum:
          - http
          - https
        default: http
      host:
        default: localhost
        description: Хост сервера
      port:
        default: "30081"
        description: Порт сервера

  # Пример предустановленных серверов
  - url: http://localhost:8081/api
    description: Локальный сервер по умолчанию

paths:
  /telemetry/{deviceId}/:
    get:
      summary: Получить список телеметрических данных
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Telemetry'
              examples:
                success:
                  summary: Пример ответа
                  value:
                    - id: "b65f14d2-4afc-4689-b8b4-f2f66b17eebd"
                      device_id: "e9f8c3ad-44ea-4f9c-8306-56003491b0c3"
                      transaction_id: "f7a3de34-5b9c-4d1e-8f2a-1c5e4d3b2a1f"
                      timestamp: "2024-12-08T14:00:00Z"
                      data:
                        temperature: 22.5
                        humidity: 45

  /telemetry/{deviceId}/temperature:
    get:
      summary: Получить телеметрию устройства
      parameters:
        - name: deviceId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Уникальный идентификатор устройства
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Telemetry'
              examples:
                success:
                  summary: Пример ответа
                  value:
                    - id: "b65f14d2-4afc-4689-b8b4-f2f66b17eebd"
                      device_id: "e9f8c3ad-44ea-4f9c-8306-56003491b0c3"
                      transaction_id: "f7a3de34-5b9c-4d1e-8f2a-1c5e4d3b2a1f"
                      timestamp: "2024-12-08T14:00:00Z"
                      data:
                        temperature: 22.5

        '404':
          description: Телеметрия для устройства не найдена
        '500':
          description: Ошибка сервера

  /telemetry:
    post:
      summary: Создать новую телеметрическую запись
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TelemetryCreate'
      responses:
        '201':
          description: Телеметрическая запись успешно создана
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Telemetry'
        '400':
          description: Некорректный запрос
        '500':
          description: Ошибка сервера

components:
  schemas:
    Telemetry:
      type: object
      properties:
        id:
          type: string
          format: uuid
        device_id:
          type: string
          format: uuid
        transaction_id:
          type: string
          format: uuid
        timestamp:
          type: string
          format: date-time
        data:
          type: object
          additionalProperties: true

    TelemetryCreate:
      type: object
      properties:
        device_id:
          type: string
          format: uuid
        transaction_id:
          type: string
          format: uuid
        timestamp:
          type: string
          format: date-time
        data:
          type: object
          additionalProperties: true