name: Build and Push Docker Images

on:
  push:
    branches:
      - project_part_2

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Build and push Docker images
      - name: Build and Push Docker Image for management-device
        run: |
          docker build -t ghcr.io/${{ github.repository }}/management-device:latest ./microservices/management-device
          docker push ghcr.io/${{ github.repository }}/management-device:latest

      - name: Build and Push Docker Image for management-telemetry
        run: |
          docker build -t ghcr.io/${{ github.repository }}/management-telemetry:latest ./microservices/management-telemetry
          docker push ghcr.io/${{ github.repository }}/management-telemetry:latest
